version: '3'
services:
  postgres:
    image: postgres:12
  django:
    build:
      context: .
      dockerfile: ./backend/compose/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - postgres
  bootstrap:
    build:
      context: .
      dockerfile: ./backend/compose/django/Dockerfile
    command: python manage.py migrate
    depends_on:
      - postgres
      - django
  react:
    build:
      context: .
      dockerfile: ./frontend/compose/node/Dockerfile
    stdin_open: true
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
